apiVersion: v1
kind: Service
metadata:
  name: {{ include "apichart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "apichart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.httpsPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "apichart.selectorLabels" . | nindent 4 }}
